In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [9]:
import requests
import pandas as pd
import time  

# List of Player IDs
player_ids = [
    1643, 2250, 1739, 10182, 8121, 12228, 8497, 7662, 8989, 
    1437, 12225, 8508, 13162, 8130, 9200, 1649, 1994, 8095, 
    7850, 7710, 8642, 8136, 6258, 9617, 2283, 10626
]


headers = {
	"x-rapidapi-key": "d09a416936msh043d6ccd23018e2p19d055jsn6eb25417d06f",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

players_data = []

# Loop through each player ID
for player_id in player_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json()
        print(f"✅ Data fetched for Player ID {player_id}")

        # Extract player name
        player_name = data.get("appIndex", {}).get("seoTitle", "").split(" Profile")[0]

        # Extract batting statistics
        stats = data.get("values", [])
        player_stats = {"Player": player_name}

        formats = ["Test", "ODI", "T20", "IPL"]

        for stat in stats:
            category = stat.get("values", [])[0]  # Get category name

            for i, format_type in enumerate(formats, start=1):
                if i < len(stat["values"]):  # Avoid index errors
                    player_stats[f"{category}_{format_type}"] = stat["values"][i]

        players_data.append(player_stats)

    else:
        print(f"⚠ Failed to fetch data for Player ID {player_id}: {response.status_code}")

    time.sleep(3)  # Add 3 seconds delay between requests

# Convert list to DataFrame
df = pd.DataFrame(players_data)
df.to_csv("cricket_players_stats.csv", index=False)

print("✅ CSV file created successfully!")

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '4', '3', '8', '0']}, {'values': ['Innings', '5', '1', '5', '0']}, {'values': ['Runs', '28', '2', '32', '0']}, {'values': ['Balls', '54', '2', '23', '0']}, {'values': ['Highest', '15', '2', '14', '0']}, {'values': ['Average', '7', '2', '0', '0']}, {'values': ['SR', '51.86', '100.00', '139.14', '0']}, {'values': ['Not Out', '1', '0', '5', '0']}, {'values': ['Fours', '3', '0', '1', '0']}, {'values': ['Sixes', '0', '0', '2', '0']}, {'values': ['Ducks', '1', '0', '0', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Mitchell Swepson Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/10626/mitchell-swepson'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 8605, 'seriesName': 'Sheffield Shield 2024-25'}]}
✅ Data fetched for Player ID 1643
✅ Data fetched for Player ID 2250
✅ Data fetched for Player ID 1739
✅ Data fetched for Player ID 10182
✅ Data fetched for Player ID 8121
✅ Data fetched for Player ID 12228
✅ Data fetched for Player ID 8497
✅ Data fetched for Player ID 7662
✅ Data fetched for Player ID 8989
✅ Data fetched for Player ID 1437
✅ Data fetched for Player ID 12225
✅ Data fetched for Player ID 8508
✅ Data fetched for Player ID 13162
✅ Data fetched for Player ID 8130
✅ Data fetched for Player ID 9200
✅ Data fetched for Player ID 1649
✅ Data fetched for Player ID 1994
✅ Data fetched for Player ID 8095
✅ Data fetched for Player ID 7850
✅ Data fetched for Player ID 7710
✅ Data fetched for Player ID 8642
✅ Data fetched for Player ID 8136
✅ Data fetched for Player ID 6258
✅ Data fetched for Player ID 9617
✅ Data fetched for Player ID 2283
✅ Data fetched for Player ID 10626
✅ CSV file created successfully!

In [10]:
df

,Player,Matches_Test,Matches_ODI,Matches_T20,Matches_IPL,Innings_Test,Innings_ODI,Innings_T20,Innings_IPL,Runs_Test,...,200s_T20,200s_IPL,300s_Test,300s_ODI,300s_T20,300s_IPL,400s_Test,400s_ODI,400s_T20,400s_IPL
0,Aaron Finch,5,146,103,92,10,142,103,90,278,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,116,170,67,103,206,154,55,93,10271,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,112,161,110,184,205,159,110,184,8786,...,0,0,1,0,0,0,0,0,0,0
3,Marnus Labuschagne,57,63,1,0,102,56,1,0,4396,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,23,6,5,0,40,6,5,0,1442,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,1,0,0,0,2,0,0,0,72,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,56,73,38,26,93,70,37,26,3719,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,7,149,116,134,14,136,106,129,339,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,71,74,96,0,64,61,88,0,...,0,0,0,0,0,0,0,0,0,0
9,Moises Henriques,4,16,24,62,8,15,21,54,164,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,28,28,13,29,43,24,12,28,1377,...,0,0,0,0,0,0,0,0,0,0
11,Ashton Agar,5,22,49,0,7,18,29,0,195,...,0,0,0,0,0,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,7,13,0,...,0,0,0,0,0,0,0,0,0,0
13,Michael Neser,2,4,0,1,3,4,0,0,56,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,39,80,38,3,57,72,26,3,1757,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,36,97,92,15,63,83,68,14,1613,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,35,35,12,2,57,35,9,2,1535,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,67,90,57,59,97,59,27,42,1454,...,0,0,0,0,0,0,0,0,0,0
18,Nathan Lyon,136,29,2,0,171,14,1,0,1595,...,0,0,0,0,0,0,0,0,0,0
19,Mitchell Starc,96,127,65,40,139,75,21,17,2217,...,0,0,0,0,0,0,0,0,0,0
20,Adam Zampa,0,111,95,21,0,55,22,5,0,...,0,0,0,0,0,0,0,0,0,0
21,Sean Abbott,0,28,20,3,0,21,7,3,0,...,0,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,72,91,52,28,88,35,10,6,510,...,0,0,0,0,0,0,0,0,0,0
23,Andrew Tye,0,7,32,30,0,7,15,13,0,...,0,0,0,0,0,0,0,0,0,0
24,James Pattinson,21,15,4,10,25,8,2,2,417,...,0,0,0,0,0,0,0,0,0,0
25,Mitchell Swepson,4,3,8,0,5,1,5,0,28,...,0,0,0,0,0,0,0,0,0,0

In [28]:
df = pd.read_csv("cricket_players_batting_stats.csv")

In [29]:
df

,Player,Matches_Test,Matches_ODI,Matches_T20,Matches_IPL,Innings_Test,Innings_ODI,Innings_T20,Innings_IPL,Runs_Test,...,200s_T20,200s_IPL,300s_Test,300s_ODI,300s_T20,300s_IPL,400s_Test,400s_ODI,400s_T20,400s_IPL
0,Aaron Finch,5,146,103,92,10,142,103,90,278,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,116,170,67,103,206,154,55,93,10271,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,112,161,110,184,205,159,110,184,8786,...,0,0,1,0,0,0,0,0,0,0
3,Marnus Labuschagne,57,63,1,0,102,56,1,0,4396,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,23,6,5,0,40,6,5,0,1442,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,1,0,0,0,2,0,0,0,72,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,56,73,38,26,93,70,37,26,3719,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,7,149,116,134,14,136,106,129,339,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,71,74,96,0,64,61,88,0,...,0,0,0,0,0,0,0,0,0,0
9,Moises Henriques,4,16,24,62,8,15,21,54,164,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,28,28,13,29,43,24,12,28,1377,...,0,0,0,0,0,0,0,0,0,0
11,Ashton Agar,5,22,49,0,7,18,29,0,195,...,0,0,0,0,0,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,7,13,0,...,0,0,0,0,0,0,0,0,0,0
13,Michael Neser,2,4,0,1,3,4,0,0,56,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,39,80,38,3,57,72,26,3,1757,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,36,97,92,15,63,83,68,14,1613,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,35,35,12,2,57,35,9,2,1535,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,67,90,57,59,97,59,27,42,1454,...,0,0,0,0,0,0,0,0,0,0
18,Nathan Lyon,136,29,2,0,171,14,1,0,1595,...,0,0,0,0,0,0,0,0,0,0
19,Mitchell Starc,96,127,65,40,139,75,21,17,2217,...,0,0,0,0,0,0,0,0,0,0
20,Adam Zampa,0,111,95,21,0,55,22,5,0,...,0,0,0,0,0,0,0,0,0,0
21,Sean Abbott,0,28,20,3,0,21,7,3,0,...,0,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,72,91,52,28,88,35,10,6,510,...,0,0,0,0,0,0,0,0,0,0
23,Andrew Tye,0,7,32,30,0,7,15,13,0,...,0,0,0,0,0,0,0,0,0,0
24,James Pattinson,21,15,4,10,25,8,2,2,417,...,0,0,0,0,0,0,0,0,0,0
25,Mitchell Swepson,4,3,8,0,5,1,5,0,28,...,0,0,0,0,0,0,0,0,0,0

In [30]:
df2 = pd.read_csv(r"C:\Users\acer\Desktop\Data Science Innomatics\ML\Projects\End-To-End\International_Cricket_Dashboard\cricket_bowlers_stats.csv")

In [31]:
df2

,Player,Test_Matches,ODI_Matches,T20_Matches,IPL_Matches,Test_Innings,ODI_Innings,T20_Innings,IPL_Innings,Test_Balls,...,T20_4w,IPL_4w,Test_5w,ODI_5w,T20_5w,IPL_5w,Test_10w,ODI_10w,T20_10w,IPL_10w
0,Aaron Finch,5,146,103,92,1,21,2,5,12,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,116,170,67,103,62,40,17,1,1470,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,112,161,110,184,19,1,0,1,342,...,0,0,0,0,0,0,0,0,0,0
3,Marnus Labuschagne,57,63,1,0,46,14,0,0,1268,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,23,6,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,56,73,38,26,37,40,4,6,855,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,7,149,116,134,9,119,76,79,462,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,71,74,96,0,64,48,62,0,...,1,1,0,0,0,0,0,0,0,0
9,Moises Henriques,4,16,24,62,4,12,10,60,330,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,28,28,13,29,44,25,12,29,2190,...,0,0,1,1,0,0,0,0,0,0
11,Ashton Agar,5,22,49,0,10,22,49,0,1006,...,0,0,0,0,2,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,10,16,0,...,0,1,0,0,0,0,0,0,0,0
13,Michael Neser,2,4,0,1,4,4,0,1,281,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,39,80,38,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,36,97,92,15,4,0,0,0,30,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,35,35,12,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,67,90,57,59,125,90,57,59,13616,...,0,1,13,1,0,0,2,0,0,0
18,Nathan Lyon,136,29,2,0,253,29,2,0,34103,...,0,0,24,0,0,0,5,0,0,0
19,Mitchell Starc,96,127,65,40,184,127,65,39,18535,...,1,2,15,9,0,0,2,0,0,0
20,Adam Zampa,0,111,95,21,0,111,94,21,0,...,2,0,0,1,1,1,0,0,0,0
21,Sean Abbott,0,28,20,3,0,28,20,3,0,...,1,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,72,91,52,28,135,90,52,28,14817,...,4,1,12,3,0,0,0,0,0,0
23,Andrew Tye,0,7,32,30,0,7,31,30,0,...,1,3,0,1,0,1,0,0,0,0
24,James Pattinson,21,15,4,10,38,15,4,10,3963,...,0,0,4,0,0,0,0,0,0,0
25,Mitchell Swepson,4,3,8,0,7,3,8,0,892,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.columns

Index(['Player', 'Matches_Test', 'Matches_ODI', 'Matches_T20', 'Matches_IPL',
       'Innings_Test', 'Innings_ODI', 'Innings_T20', 'Innings_IPL',
       'Runs_Test', 'Runs_ODI', 'Runs_T20', 'Runs_IPL', 'Balls_Test',
       'Balls_ODI', 'Balls_T20', 'Balls_IPL', 'Highest_Test', 'Highest_ODI',
       'Highest_T20', 'Highest_IPL', 'Average_Test', 'Average_ODI',
       'Average_T20', 'Average_IPL', 'SR_Test', 'SR_ODI', 'SR_T20', 'SR_IPL',
       'Not Out_Test', 'Not Out_ODI', 'Not Out_T20', 'Not Out_IPL',
       'Fours_Test', 'Fours_ODI', 'Fours_T20', 'Fours_IPL', 'Sixes_Test',
       'Sixes_ODI', 'Sixes_T20', 'Sixes_IPL', 'Ducks_Test', 'Ducks_ODI',
       'Ducks_T20', 'Ducks_IPL', '50s_Test', '50s_ODI', '50s_T20', '50s_IPL',
       '100s_Test', '100s_ODI', '100s_T20', '100s_IPL', '200s_Test',
       '200s_ODI', '200s_T20', '200s_IPL', '300s_Test', '300s_ODI', '300s_T20',
       '300s_IPL', '400s_Test', '400s_ODI', '400s_T20', '400s_IPL'],
      dtype='object')

In [32]:
exclude_columns = ["Player", "Matches_Test", "Matches_ODI", "Matches_T20", "Matches_IPL"]


df.rename(
    columns={col: f"batting_{col}" if col not in exclude_columns else col for col in df.columns},
    inplace=True
)

In [33]:
df

,Player,Matches_Test,Matches_ODI,Matches_T20,Matches_IPL,batting_Innings_Test,batting_Innings_ODI,batting_Innings_T20,batting_Innings_IPL,batting_Runs_Test,...,batting_200s_T20,batting_200s_IPL,batting_300s_Test,batting_300s_ODI,batting_300s_T20,batting_300s_IPL,batting_400s_Test,batting_400s_ODI,batting_400s_T20,batting_400s_IPL
0,Aaron Finch,5,146,103,92,10,142,103,90,278,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,116,170,67,103,206,154,55,93,10271,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,112,161,110,184,205,159,110,184,8786,...,0,0,1,0,0,0,0,0,0,0
3,Marnus Labuschagne,57,63,1,0,102,56,1,0,4396,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,23,6,5,0,40,6,5,0,1442,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,1,0,0,0,2,0,0,0,72,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,56,73,38,26,93,70,37,26,3719,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,7,149,116,134,14,136,106,129,339,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,71,74,96,0,64,61,88,0,...,0,0,0,0,0,0,0,0,0,0
9,Moises Henriques,4,16,24,62,8,15,21,54,164,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,28,28,13,29,43,24,12,28,1377,...,0,0,0,0,0,0,0,0,0,0
11,Ashton Agar,5,22,49,0,7,18,29,0,195,...,0,0,0,0,0,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,7,13,0,...,0,0,0,0,0,0,0,0,0,0
13,Michael Neser,2,4,0,1,3,4,0,0,56,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,39,80,38,3,57,72,26,3,1757,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,36,97,92,15,63,83,68,14,1613,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,35,35,12,2,57,35,9,2,1535,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,67,90,57,59,97,59,27,42,1454,...,0,0,0,0,0,0,0,0,0,0
18,Nathan Lyon,136,29,2,0,171,14,1,0,1595,...,0,0,0,0,0,0,0,0,0,0
19,Mitchell Starc,96,127,65,40,139,75,21,17,2217,...,0,0,0,0,0,0,0,0,0,0
20,Adam Zampa,0,111,95,21,0,55,22,5,0,...,0,0,0,0,0,0,0,0,0,0
21,Sean Abbott,0,28,20,3,0,21,7,3,0,...,0,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,72,91,52,28,88,35,10,6,510,...,0,0,0,0,0,0,0,0,0,0
23,Andrew Tye,0,7,32,30,0,7,15,13,0,...,0,0,0,0,0,0,0,0,0,0
24,James Pattinson,21,15,4,10,25,8,2,2,417,...,0,0,0,0,0,0,0,0,0,0
25,Mitchell Swepson,4,3,8,0,5,1,5,0,28,...,0,0,0,0,0,0,0,0,0,0

In [34]:
exclude_columns = ["Player", "Test_Matches", "ODI_Matches", "T20_Matches", "IPL_Matches"]


df2.rename(
    columns={col: f"bowling_{col}" if col not in exclude_columns else col for col in df2.columns},
    inplace=True
)

In [35]:
df2

,Player,Test_Matches,ODI_Matches,T20_Matches,IPL_Matches,bowling_Test_Innings,bowling_ODI_Innings,bowling_T20_Innings,bowling_IPL_Innings,bowling_Test_Balls,...,bowling_T20_4w,bowling_IPL_4w,bowling_Test_5w,bowling_ODI_5w,bowling_T20_5w,bowling_IPL_5w,bowling_Test_10w,bowling_ODI_10w,bowling_T20_10w,bowling_IPL_10w
0,Aaron Finch,5,146,103,92,1,21,2,5,12,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,116,170,67,103,62,40,17,1,1470,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,112,161,110,184,19,1,0,1,342,...,0,0,0,0,0,0,0,0,0,0
3,Marnus Labuschagne,57,63,1,0,46,14,0,0,1268,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,23,6,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,56,73,38,26,37,40,4,6,855,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,7,149,116,134,9,119,76,79,462,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,71,74,96,0,64,48,62,0,...,1,1,0,0,0,0,0,0,0,0
9,Moises Henriques,4,16,24,62,4,12,10,60,330,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,28,28,13,29,44,25,12,29,2190,...,0,0,1,1,0,0,0,0,0,0
11,Ashton Agar,5,22,49,0,10,22,49,0,1006,...,0,0,0,0,2,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,10,16,0,...,0,1,0,0,0,0,0,0,0,0
13,Michael Neser,2,4,0,1,4,4,0,1,281,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,39,80,38,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,36,97,92,15,4,0,0,0,30,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,35,35,12,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,67,90,57,59,125,90,57,59,13616,...,0,1,13,1,0,0,2,0,0,0
18,Nathan Lyon,136,29,2,0,253,29,2,0,34103,...,0,0,24,0,0,0,5,0,0,0
19,Mitchell Starc,96,127,65,40,184,127,65,39,18535,...,1,2,15,9,0,0,2,0,0,0
20,Adam Zampa,0,111,95,21,0,111,94,21,0,...,2,0,0,1,1,1,0,0,0,0
21,Sean Abbott,0,28,20,3,0,28,20,3,0,...,1,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,72,91,52,28,135,90,52,28,14817,...,4,1,12,3,0,0,0,0,0,0
23,Andrew Tye,0,7,32,30,0,7,31,30,0,...,1,3,0,1,0,1,0,0,0,0
24,James Pattinson,21,15,4,10,38,15,4,10,3963,...,0,0,4,0,0,0,0,0,0,0
25,Mitchell Swepson,4,3,8,0,7,3,8,0,892,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df2.drop(columns=["Test_Matches","ODI_Matches","T20_Matches","IPL_Matches"],inplace=True)

In [37]:
df2

,Player,bowling_Test_Innings,bowling_ODI_Innings,bowling_T20_Innings,bowling_IPL_Innings,bowling_Test_Balls,bowling_ODI_Balls,bowling_T20_Balls,bowling_IPL_Balls,bowling_Test_Runs,...,bowling_T20_4w,bowling_IPL_4w,bowling_Test_5w,bowling_ODI_5w,bowling_T20_5w,bowling_IPL_5w,bowling_Test_10w,bowling_ODI_10w,bowling_T20_10w,bowling_IPL_10w
0,Aaron Finch,1,21,2,5,12,284,12,43,8,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,62,40,17,1,1470,1076,291,2,1008,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,19,1,0,1,342,6,0,1,269,...,0,0,0,0,0,0,0,0,0,0
3,Marnus Labuschagne,46,14,0,0,1268,281,0,0,795,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,37,40,4,6,855,1125,36,58,515,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,9,119,76,79,462,4002,985,944,341,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,64,48,62,0,2071,750,803,0,...,1,1,0,0,0,0,0,0,0,0
9,Moises Henriques,4,12,10,60,330,402,138,950,164,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,44,25,12,29,2190,814,188,439,1236,...,0,0,1,1,0,0,0,0,0,0
11,Ashton Agar,10,22,49,0,1006,1098,1042,0,468,...,0,0,0,0,2,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,180,360,0,...,0,1,0,0,0,0,0,0,0,0
13,Michael Neser,4,4,0,1,281,220,0,24,117,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,4,0,0,0,30,0,0,0,28,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,125,90,57,59,13616,4683,1254,1343,6597,...,0,1,13,1,0,0,2,0,0,0
18,Nathan Lyon,253,29,2,0,34103,1626,30,0,16699,...,0,0,24,0,0,0,5,0,0,0
19,Mitchell Starc,184,127,65,39,18535,6512,1458,831,10534,...,1,2,15,9,0,0,2,0,0,0
20,Adam Zampa,0,111,94,21,0,5777,2057,443,0,...,2,0,0,1,1,1,0,0,0,0
21,Sean Abbott,0,28,20,3,0,1307,367,54,0,...,1,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,135,90,52,28,14817,4737,1186,627,6857,...,4,1,12,3,0,0,0,0,0,0
23,Andrew Tye,0,7,31,30,0,387,683,684,0,...,1,3,0,1,0,1,0,0,0,0
24,James Pattinson,38,15,4,10,3963,727,78,213,2133,...,0,0,4,0,0,0,0,0,0,0
25,Mitchell Swepson,7,3,8,0,892,158,150,0,458,...,0,0,0,0,0,0,0,0,0,0

In [38]:
data=pd.merge(df,df2,how="outer",on="Player")

In [39]:
data

,Player,Matches_Test,Matches_ODI,Matches_T20,Matches_IPL,batting_Innings_Test,batting_Innings_ODI,batting_Innings_T20,batting_Innings_IPL,batting_Runs_Test,...,bowling_T20_4w,bowling_IPL_4w,bowling_Test_5w,bowling_ODI_5w,bowling_T20_5w,bowling_IPL_5w,bowling_Test_10w,bowling_ODI_10w,bowling_T20_10w,bowling_IPL_10w
0,Aaron Finch,5,146,103,92,10,142,103,90,278,...,0,0,0,0,0,0,0,0,0,0
1,Steven Smith,116,170,67,103,206,154,55,93,10271,...,0,0,0,0,0,0,0,0,0,0
2,David Warner,112,161,110,184,205,159,110,184,8786,...,0,0,0,0,0,0,0,0,0,0
3,Marnus Labuschagne,57,63,1,0,102,56,1,0,4396,...,0,0,0,0,0,0,0,0,0,0
4,Joe Burns,23,6,5,0,40,6,5,0,1442,...,0,0,0,0,0,0,0,0,0,0
5,Will Pucovski,1,0,0,0,2,0,0,0,72,...,0,0,0,0,0,0,0,0,0,0
6,Travis Head,56,73,38,26,93,70,37,26,3719,...,0,0,0,0,0,0,0,0,0,0
7,Glenn Maxwell,7,149,116,134,14,136,106,129,339,...,0,0,0,0,0,0,0,0,0,0
8,Marcus Stoinis,0,71,74,96,0,64,61,88,0,...,1,1,0,0,0,0,0,0,0,0
9,Moises Henriques,4,16,24,62,8,15,21,54,164,...,0,0,0,0,0,0,0,0,0,0
10,Cameron Green,28,28,13,29,43,24,12,28,1377,...,0,0,1,1,0,0,0,0,0,0
11,Ashton Agar,5,22,49,0,7,18,29,0,195,...,0,0,0,0,2,0,0,0,0,0
12,Daniel Sams,0,0,10,16,0,0,7,13,0,...,0,1,0,0,0,0,0,0,0,0
13,Michael Neser,2,4,0,1,3,4,0,0,56,...,0,0,0,0,0,0,0,0,0,0
14,Alex Carey,39,80,38,3,57,72,26,3,1757,...,0,0,0,0,0,0,0,0,0,0
15,Matthew Wade,36,97,92,15,63,83,68,14,1613,...,0,0,0,0,0,0,0,0,0,0
16,Tim Paine,35,35,12,2,57,35,9,2,1535,...,0,0,0,0,0,0,0,0,0,0
17,Pat Cummins,67,90,57,59,97,59,27,42,1454,...,0,1,13,1,0,0,2,0,0,0
18,Nathan Lyon,136,29,2,0,171,14,1,0,1595,...,0,0,24,0,0,0,5,0,0,0
19,Mitchell Starc,96,127,65,40,139,75,21,17,2217,...,1,2,15,9,0,0,2,0,0,0
20,Adam Zampa,0,111,95,21,0,55,22,5,0,...,2,0,0,1,1,1,0,0,0,0
21,Sean Abbott,0,28,20,3,0,21,7,3,0,...,1,0,0,0,0,0,0,0,0,0
22,Josh Hazlewood,72,91,52,28,88,35,10,6,510,...,4,1,12,3,0,0,0,0,0,0
23,Andrew Tye,0,7,32,30,0,7,15,13,0,...,1,3,0,1,0,1,0,0,0,0
24,James Pattinson,21,15,4,10,25,8,2,2,417,...,0,0,4,0,0,0,0,0,0,0
25,Mitchell Swepson,4,3,8,0,5,1,5,0,28,...,0,0,0,0,0,0,0,0,0,0

In [40]:
data.to_csv("Australia.csv",index=False)